[package]
name = "rust_2024_21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.55.1"
itertools = "0.14.0"
relative-path = "1.9.2"
