[package]
name = "rust_2024_19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.55.1"
regex = "1.11.1"
relative-path = "1.9.2"
